### ISSUE TITLE
CronJob to periodically run analyze table on every table

### ISSUE THREAD

**Issue by shinnosuke-okada** [pingcap/tidb-operator#1026]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It is commonly suggested to run `analyze table` daily on every table to keep the metadata up-to-date. Currently, users would need to write their own script and automation to perform this task. As per discussion with Gin (Tianshuang), we think that it'd be beneficial to package this task as a k8s CronJob as part of `tidb-cluster` helm chart.

**Describe the feature you'd like:**

Add a new k8s CronJob that runs `analyze table` on all tables to `tidb-cluster` helm chart.

**Describe alternatives you've considered:**

Set up and deploy the same CronJob on our own.

**Teachability, Documentation, Adoption, Migration Strategy:**

Just like how customers currently use the scheduled backup CronJob, the feature should be enabled/disabled with a boolean flag, and customizable with some parameters.

**Comment by shinnosuke-okada** [comment]
Since we'd need to setup our own k8s CronJob anyway, I'd be happy to contribute the code for this feature - just let me know.

**Comment by tennix** [comment]
@shinnosuke-okada Thank you for your suggestion! There might be other options to achieve this, for example if TiDB can have an auto analyzing configuration, then users don't have to do this externally. We'll discuss this with the TiDB team to see if it's possible to do it inside of TiDB.

Note that since the helm chart is not friendly for API integration which is required for many users that want to build a database platform, we'll adopting aggregated apiserver https://github.com/pingcap/tidb-operator/issues/1002. Eventually, we'll provide simple APIs to manage TiDB clusters. That way the helm chart is not mandatory.

**Comment by shinnosuke-okada** [comment]
@tennix: Yes, handling this within TiDB or handling it via apiserver makes more sense. Thanks for sharing the current situation, and please let us know if we can help in any way.

I'll keep this ticket open as a reminder for the use case. Feel free to recreate or edit the ticket once the direction is clear.
