### ISSUE TITLE
Cross k8s deployment

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1117]
## Feature Request

Since [Kubernetes federation v1 is strongly discouraged](https://kubernetes.io/docs/concepts/cluster-administration/federation/), and [v2 is still under heavy development](https://github.com/kubernetes-sigs/kubefed). Users may deploy a Kubernetes per DC, and want to leverage TiDB's [cross DC falt-tolerance](https://pingcap.com/docs/v3.0/how-to/deploy/geographic-redundancy/location-awareness/#pd-understands-the-tikv-topology) ability. Currently, tidb-operator doesn't support this deployment. It would be useful to have support cross k8s deployment for a single TiDB cluster.

Usually, users will make the pods in different k8s cluster connect with each other via pod IP directly. With this assumption, if the cluster DNS records can be propagated to different k8s clusters, then it's possible to deploy a TiDB cluster cross k8s clusters. A possible solution is running tidb-operator to watch resources in different k8s clusters.

close #565

**Comment by gregwebs** [comment]
> A possible solution is running tidb-operator to watch resources in different k8s clusters.
Would it then have access to the K8s API in the other data center?

if the goal is cross-DC fault tolerance, than the ideal would be to deploy tidb-operator in all DCs and have it manage the TiDB pods in its DC. Otherwise if a DC goes down it may take tidb-operator with it.

It seems like it should be possible to have a separate tidb-operator deployment in each datacenter where tidb-operator does *not* communicate cross-DC. Instead the user would make separate tidb-operator deployments to each datacenter. They would add an additional configuration to mention that there is an additional PD service for PD to connect to to form its cluster (that additional service comes from the DNS propagation from the other server). 

 tidb-operator would just need to be able to run just 1 PD or 2 PD in its DC and ask PD about the total number of PD in the PD cluster, verifying that the additional PD not controlled by tidb-operator are outside of tidb-operator's datacenter (k8s cluster).

There would be no automatic failover actions by tidb-operator when another DC goes down: the user would have to respond to this manually.

@c4pt0r said he imagines a 1 tidb-operator for each k8s cluster.

**Comment by tennix** [comment]
We can deploy a tidb-operator in each k8s cluster, and using a leader lock to allow only one tidb-operator work at a time. When a DC fails, another tidb-operator takes over the operation work.

**Comment by gregwebs** [comment]
> We can deploy a tidb-operator in each k8s cluster, and  using a leader lock to allow only one tidb-operator work at a time. When  a DC fails, another tidb-operator takes over the operation work.

Yes. But this is going to end up getting complicated: what do you do when there is a network partition between the k8s clusters?

My suggestion is to avoid these issues by having no coordination among the tidb-operators running and have each tidb-operator be actively managing just its own k8s cluster.

**Comment by aylei** [comment]
This will help addressing: https://github.com/pingcap/tidb-operator/issues/565

**Comment by mehrdadrad** [comment]
does k8s cluster mesh, like cilium help?

**Comment by tennix** [comment]
> does k8s cluster mesh, like cilium help?

@Yisaer PTAL
