### ISSUE TITLE
Feature Request: Add common wait-unit init-container 

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#1255]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently we need a common wait-unit init container for `tidb-initializer` / ~~`tikv` / `tidb`~~ (`pump` and `drainer`) to wait until their dependency ready. We also want it to have a `timeout` configuration in order to avoid wating forever.

**Comment by gregwebs** [comment]
This is already developed on this PR: https://github.com/pingcap/tidb-operator/pull/581
Also the discovery service is more developed on this PR: https://github.com/pingcap/tidb-operator/pull/935

**Comment by Yisaer** [comment]
Hi @gregwebs , I checked the pr #581 and found the `wait-for-pd` might be more uncommon or complex for this feature request.

I think a `busybox` image with `nc` checking whether the target port was opened is enough for a common wait-until init container.

**Comment by cofyc** [comment]
we need to wait for the `host:port` of TiDB service is ready (as @Yisaer said a simple TCP port check is enough) before trying to run commands in `tidb-initializer`, `pump` and `drainer` (the description has been updated) because the kubelet will wait more and more time to restart these pods to retry if they fail fast many times and we can't configure restart backoff time in k8s.

**Comment by gregwebs** [comment]
Yes that sounds great for TiDB. Then my endpoint ready check for TiDB initializer would work properly.

**Comment by cofyc** [comment]
I'm going to add support for tidb-initializer (https://github.com/pingcap/tidb-operator/pull/1296). This saves my time in local development.
