### ISSUE TITLE
Under the Host mode,the advertise address should use host machine name

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#1300]
## Bug Report

**What version of Kubernetes are you using?**
v1.14.8

**What version of TiDB Operator are you using?**
1.0.4

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
I use host mode deploying tidb cluster.

**What did you expect to see?**
When deploying with host mode ,I think the `--advertise-addr` config should use host machine name.
Because I use host mode ,just want to use the host's domain name. My client connect to pd, I also need to aceess k8s dns domain.And external machine can't reslove k8s dns domain.So if the 
 `--advertise-addr` config not use hostname,the host mode is useless.

And I want to modify the code to fix this
I think I need modify files below:
```
modify --advertise-addr config into 
_start_pd.sh.tpl
_start_tidb.sh.tpl
_start_tikv.sh.tpl
```
What else do I need to change ?

**What did you see instead?**
Under the Host mode,the advertise address should use host machine name

**Comment by aylei** [comment]
Thanks for the detailed report! 

Actually, `advertise-addr` is not only the address for client communication but also an **ID** of  a tikv-server instance. We cannot rely on the host to provide a consistent hostname, neither could we expect a TiKV instance to be bound to a host and never get rescheduled. Therefore, choose a stable ID, e.g. `POD_NAME` we're currently using is necessary.

IMHO, this issue is better to be addressed in the TiKV side: TiKV can break the tight couple of instance identity and the address for client communicating because the latter one is not forced to be stable and it could help a lot in the cloud env.

cc @cofyc @tennix

**Comment by mikechengwei** [comment]
I understand,with the help of k8s automatic discovery, failover is nice to implement.
Let me think it over.
