### ISSUE TITLE
last applied pod template of statefulset will trigger rolling-update unexpectedly

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1340]
## Bug Report

https://github.com/pingcap/tidb-operator/pull/1287 fix a compatiability issue of tidb-operator. However, in Kubernetes, `dnsPolicy` is default to `ClusterFirst`, so setting this field explicitly to `ClusterFirst` is compatible with leaving it as empty. The change that triggers rolling update is happened in the `.spec.template.annotation[last-applied-config]` field, which marshals the un-defaulted Pod template.

We should move this annotation from `.spec.template.annotations` to `.annotations` to avoid more cases like #1287 .

Existing `.spec.template.annotation[last-applied-config]` will be retained to keep backward compatibility but no longer be read.

ref: https://github.com/pingcap/tidb-operator/issues/1335

**Comment by cofyc** [comment]
it's possible to check `sts.annotations[last-applied-config]` only because it contains `sts.spec.template`, but it cannot avoid this issue because the configuration we store is the client data.

this issue will be avoided when we migrated `Upgrader` logic to webhook. In that case, whether to trigger upgrade logic for our components is decided by statefulset controller which will not upgrade the pod to set the `dnsPolicy` explicitly.

**Comment by aylei** [comment]
@cofyc IIUC, if we remove pod-template annotation from the pod template, though we will still upgrade the sts in controller, but the hash of pod template won't change

**Comment by cofyc** [comment]
annotations change in `statefulset.spec.template` will upgrade pod because they need to be copied to pod object

**Comment by aylei** [comment]
@cofyc Exactly, so I am going to remove the `last-applied-xx` annotations in `statefulset.spec.template`
