### ISSUE TITLE
Move tikv-importer to lightning chart

### ISSUE THREAD

**Issue by shonge** [pingcap/tidb-operator#1534]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Importer in tidb-cluster chart and it work need lightning together, so maybe we should move it to the lightning chart. 

**Describe the feature you'd like:**

Install or remove lightning/importer in one step.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Yisaer** [comment]
As we are moving attention from helm chart to CRD Object, the new feature request or refactor is preferred to be done in CRD Object. What's your opinion? @aylei

**Comment by DanielZhangQD** [comment]
I think no need to create CRD and controller for lightning and importer since they are just one-time deal tools.
Lightning does not have to work together with the importer, it supports two backends - tidb/mysql (https://pingcap.com/docs/stable/reference/tools/tidb-lightning/tidb-backend/) and importer.
But from v1.1, tidb cluster is migrated to CRD, and now we cannot install importer with helm, I think we can add tikv-importer to lightning chart and with `enable` to control whether to deploy importer when deploying lightning.

DBaaS may need this when switching to operator v1.1.
Please also note that tikv-importer will be integrated into tikv in the tool's roadmap, however, we are not sure when will that be completed.

**Comment by DanielZhangQD** [comment]
@shonge Suggest adding a new chart for tikv-importer instead of updating the chart of tidb-lightning since they do not need to be deployed together.
