### ISSUE TITLE
e2e test doesn't work with default version of bash on macOS

### ISSUE THREAD

**Issue by longfangsong** [pingcap/tidb-operator#1560]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When run `./hack/e2e.sh` with the default bash on macOS (version 3.2), there's a error message:
```bash
./hack/e2e.sh: line 136: declare: -A: invalid option
```

It is because bash v3.2 doesn't support `declare  -A`. 

Either the developer should upgrade their bash or some shell script which compatible with bash v3.2 should be used here.

**Describe the feature you'd like:**

Use a method which also works in bash v3.2 or describe this in doc.

**Comment by cofyc** [comment]
yes, it's better we can support bash version < 4. the problem is bash 3 is too old, many new features in bash 4+ can simplify the shell script. here are some alternative solutions:

1)  run `hack/run-in-container.sh` to start a `dev` container with the same environment we used in CI. this is recommended because the only dependency is docker and every developer can have the same development environment
2) install bash 4+, e.g. `brew install bash`, our script use `#!/usr/bin/env bash` Shebang to use the first bash in `PATH`

**Comment by cofyc** [comment]
so right now, I prefer to describe this requirement in doc, can you send a PR for it? 
also we can check the bash version in the script and print a more useful message for the developer.

**Comment by longfangsong** [comment]
@cofyc working on checking the bash version
