### ISSUE TITLE
the pod of pd or tikv will be pending when there are three nodes in k8s and replicas which is set by tc are above 3 

### ISSUE THREAD

**Issue by zhuboshuai** [pingcap/tidb-operator#1594]
## Bug Report

**What version of Kubernetes are you using?**
v1.16.3

**What version of TiDB Operator are you using?**
v1.0.5

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**
local-storage

**What's the status of the TiDB cluster pods?**
tidbcluster-wuhanwuli-tikv-0                       0/1     Pending     0          11d
tidbcluster-wuhanwuli-tikv-1                       1/1     Running     17         12d
tidbcluster-wuhanwuli-tikv-2                       1/1     Running     18         12d
tidbcluster-wuhanwuli-tikv-3                       0/1     Pending     0          12d

**What did you do?**
there are 3 nodes in k8s. make a node down, then use a new server to recover the node, make new pv in the new node.

**What did you expect to see?**
all the tikv's pods can become running

**What did you see instead?**
some of the tikv's pods are pending, unless add new nodes and new pv

**Comment by aylei** [comment]
could you provide the log of tidb-scheduler and the result of `kubectl describe po tidbcluster-wuhanwuli-tikv-3`

**Comment by cofyc** [comment]
we had discussed this issue offline, the root cause is when a failover happens, the statefulset of tikv is increased (3 -> 4)
because the desired replicas of tidb cluster does not change, only one pod is allowed on each node in tidb-scheduler HA predicate.

a possible solution is checking the desired replicas of statefulset instead of tidb cluster CRD. 

cc @weekface what do you think?

**Comment by weekface** [comment]
agree, we may use `.spec.tikv.replicas + len(.status.tikv.failureStores)` as desired replicas
