### ISSUE TITLE
happen error when discovery mechanism return response

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#1764]
## Bug Report

**What version of Kubernetes are you using?**
1.14.3

**What version of TiDB Operator are you using?**
1.0.6

**What did you do?**
When I install a tidb cluster, I find error below:
![异常](https://user-images.githubusercontent.com/13257127/75155382-e89cad80-574a-11ea-9e40-0452354bb42a.png)

` failed to writeError: Get http://app-pd-peer.tikv:2379/pd/api/v1/members`
I think pd peer url only config `2380` port , according to log, discovery use `2379` port to return resp.
The code below:
https://github.com/pingcap/tidb-operator/blob/271cad3259fab5e26123a38888c90edcb7cdec10/pkg/discovery/server/mux.go#L60

**What did you expect to see?**
We need add `2380` port to pd peer url service config.

**Comment by DanielZhangQD** [comment]
@mikechengwei Could you please share in which scenario that this issue happened?
Did you resolve this issue?

**Comment by mikechengwei** [comment]
I think we can try to  add `2379 `port in app-pd-peer service. The discovery response return use `2379` port.

**Comment by mikechengwei** [comment]
Sometimes , discovery return happen error，it  may be the cause of the network, will it be the cause of the port?

**Comment by cofyc** [comment]
do you have this issue in `1.1.0-rc.1`?

**Comment by cofyc** [comment]
by the way, as @DanielZhangQD said, pleas describe how to reproduce this issue. We don't have seen this issue before, and don't understand how to reproduce this. Actually, ports configured on the service are not the ONLY ports that can be accessed. As for headless service, actually there is no service IP, the client will connect to `<port-ip>:2379` directly. If `2379` is not connectable, the root cause should not be the service config.

**Comment by mikechengwei** [comment]
It is more difficult to analyze ,i will continue to analyze this question and close this pr firstly
