### ISSUE TITLE
A question about cluster running status

### ISSUE THREAD

**Issue by Sullivan12138** [pingcap/tidb-operator#2092]
The replica number in my  yaml file of tikv and pd is 3. But when the cluster starts for a while, 3 more tikv pods and 3 more pd pods are created, and they are all pending. What's the problem?
![image](https://user-images.githubusercontent.com/44030194/78096693-e219e980-740c-11ea-8641-368ea86dbc90.png)

![image](https://user-images.githubusercontent.com/44030194/78096814-38872800-740d-11ea-9ef5-285fd3b6bd44.png)
![image](https://user-images.githubusercontent.com/44030194/78096779-1c838680-740d-11ea-84e5-5c22d5631782.png)

**Comment by cofyc** [comment]
I guess it's the auto-failover replicas created by [auto-failover controller](https://pingcap.com/docs-cn/tidb-in-kubernetes/stable/use-auto-failover/) and they are pending because no nodes can fit them.

The default max auto-failover count is `3` in `tidb-cluster` chart.

https://github.com/pingcap/tidb-operator/blob/38d2a865273e1af8d4e6d38d3162aea4d28305cf/charts/tidb-cluster/templates/tidb-cluster.yaml#L96

Can you provide the yaml of `tc` object?

```
kubect -n test-tidb2 tc test-tidb2 -o yaml
```

You can remove `failureStores` under `status.tikv` and `failureMembers` under `status.pd`. When they are going from the status, auto-failover replicas will be deleted.

By the way, what tidb operator version you are using now? In [v1.1.0-rc.1](https://github.com/pingcap/tidb-operator/releases/tag/v1.1.0-rc.1), you can set `pd.maxFailoverCount` and `tikv.maxFailoverCount` to `0` to disable this feature.
