### ISSUE TITLE
Parse pd member id failed

### ISSUE THREAD

**Issue by xiaojingchen** [pingcap/tidb-operator#238]
when operator call the api of delete pd member, happen the error of `out of range` error ,
the error logs:
```
E1218 09:52:42.464090       1 tidb_cluster_controller.go:239] TidbCluster: example2/example2, sync failed strconv.Atoi: parsing "12891273174085095651": value out of range, requeuing
```

**Comment by weekface** [comment]
https://github.com/pingcap/tidb-operator/blob/4c183422345d8fe9e5a450f3729339ee01684767/pkg/manager/member/pd_failover.go#L160

"12891273174085095651" is too big for `Int`, so we must use `strconv.ParseUint` instead of `strconv.Atoi`

https://github.com/pingcap/tidb-operator/blob/1bc6486d27ac323d73a9de00c7a1cd187d658442/pkg/controller/pd_control.go#L345

Get the member again to ensure it is not found if deleting failed. Here is an example: https://github.com/pingcap/tidb-operator/blob/1bc6486d27ac323d73a9de00c7a1cd187d658442/pkg/controller/pd_control.go#L400-L415
