### ISSUE TITLE
Procedure to access TiDB dashboard with TLS enabled

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#2395]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, it's not easy to access TiDB dashboard with TLS enabled.
**Describe the feature you'd like:**

A Procedure to access TiDB dashboard with TLS enabled.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
Nginx ingress controller supports TLS with backend service:
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-certificate-authentication

**Comment by Yisaer** [comment]
I tried some annotation list on the previous document and it seems not work. Maybe the nginx controller we use have a lower version or I use it in a wrong way. 

I think providing a more common way to expose the dashboard service instead of using the advance ability in nginx controller (besides, nginx is not the only way for the ingress controller). I'd like to use a proxy server(eg: discovery service) to proxy the dashboard service.

The discovery service would expose the dashboard service with http and hide the logic between the proxy server and the dashboard service (enable tls or not). In this way, we could use the basic ability of the Ingress to expose the dashboard service and user will use dashboard with ignoring whether tls enabled or not.
