### ISSUE TITLE
hack/local-up-operator.sh is missing kube-schedule image

### ISSUE THREAD

**Issue by zjj2wry** [pingcap/tidb-operator#2591]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**
```bash
➜  ~ kubectl get all -n pingcap
NAME                                           READY   STATUS             RESTARTS   AGE
pod/tidb-controller-manager-79c9f8b77b-8lbdb   1/1     Running            0          38m
pod/tidb-scheduler-65b5986796-pmvlz            1/2     ImagePullBackOff   0          38m
```
```bash
  Warning  Failed     40m (x4 over 41m)      kubelet, kind-control-plane  Failed to pull image "k8s.gcr.io/kube-scheduler:v1.19.0": rpc error: code = NotFound desc = failed to pull and unpack image "k8s.gcr.io/kube-scheduler:v1.19.0": failed to resolve reference "k8s.gcr.io/kube-scheduler:v1.19.0": k8s.gcr.io/kube-scheduler:v1.19.0: not found
  Warning  Failed     40m (x4 over 41m)      kubelet, kind-control-plane  Error: ErrImagePull
  Warning  Failed     6m51s (x153 over 41m)  kubelet, kind-control-plane  Error: ImagePullBackOff
  Normal   BackOff    116s (x175 over 41m)   kubelet, kind-control-plane  Back-off pulling image "k8s.gcr.io/kube-scheduler:v1.19.0"
```

**Comment by cofyc** [comment]
what's your Kubernetes version? if you start a dev version, e.g. kubernetes built on the master branch. hack/local-up-operator.sh may fail with this error, because Kubernetes 1.19 is not released yet. Currently, `hack/local-up-operator.sh` does not support customizing operator values. You can 

1) start a released Kubernetesion version by kind, e.g. 1.18.2
2) update `hack/local-up-operator.sh` locally  to use a publicly available image, e.g. pass `--set-string schedulerkubeSchedulerImageName=k8s.gcr.io/kube-scheduler:v1.18.2` helm value

**Comment by cofyc** [comment]
btw, if you didn't use the unreleased v1.19.0 version, please provide more information about your environments, e.g. kind version, the commands, and output.

**Comment by zjj2wry** [comment]
@cofyc my kind cluster built by the kubernetes master branch. I think the main reason is that the chart should use the existing kube-schedule image in the cluster. I think the image tag should use GitVersion directly.

```
-        image: {{ required "scheduler.kubeSchedulerImageName is required" .Values.scheduler.kubeSchedulerImageName }}:{{ .Values.scheduler.kubeSchedulerImageTag | default (split "-" .Capabilities.KubeVersion.GitVersion)._0 }}
+        image: {{ required "scheduler.kubeSchedulerImageName is required" .Values.scheduler.kubeSchedulerImageName }}:{{ .Values.scheduler.kubeSchedulerImageTag | default .Capabilities.KubeVersion.GitVersion }}
```

**Comment by cofyc** [comment]
it makes sense in this scenario.
@weekface what do you think?

**Comment by cofyc** [comment]
oh, using the full git version as the image tag will not work in GKE/EKS environments, because they have built their k8s version too, e.g. 

```
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

The full version is `v1.15.11-eks-af3caf`, but `k8s.gcr.io/kube-scheduler:v1.15.11-eks-af3caf` does not exist. I guess this is the reason why we dropped the `-` suffix. So it's better not to change this behavior as it won't work in some production scenarios.

Can you add an option or an environment in `hack/local-up-operator.sh` to configure tidb-operator chart values? Then developers can use customized deployment values.

**Comment by cofyc** [comment]
or you can hack for kind environment in `hack/local-up-operator.sh`, e.g. 1) get kind k8s version 2) set it to `scheduler.kubeSchedulerImageTag`

**Comment by zjj2wry** [comment]
I agree to use an official version of the tag, my scenario is very special. This issue will only appear when the k8s cluster version used by the user has not been officially released.

@cofyc thanks
/close
