### ISSUE TITLE
Relax hyperkube version match requirement?

### ISSUE THREAD

**Issue by kkimdev** [pingcap/tidb-operator#278]
Currently users are supposed to match hyperkube's version to Kubernetes' version by `--set scheduler.kubeSchedulerImage=gcr.io/google-containers/hyperkube:${KUBE_VERSION}`

However, some managed Kubernetes service provides automatic Kubernetes version upgrade which can introduce version mismatch overnight.  It would be great if this exact version match requirement can be relaxed.

I don't know the technical feasibility about this though.

**Comment by gregwebs** [comment]
I think it should be possible for us to default to matching what K8s is running (and even track if it changes)

**Comment by weekface** [comment]
@kkimdev The pods created by TiDB Operator are scheduled by TiDB Scheduler(kube-scheduler + tidb-scheduler). We recommend keeping consistent, but these two versions can be different actually.

**Comment by gregwebs** [comment]
Major version changes of k8s will definitely break this setup.
We can use either helm Capabilities.KubeVersion or a MutatingAdmissionWebhook to set the image tag to match K8s so that the user does not configure this parameter.
The helm approach would require the user to do a helm upgrade when ugprading the K8s version.

Otherwise we would need some code to monitor the K8s version and change the image tag when the K8s version changes.

**Comment by gregwebs** [comment]
We now default the helm chart to try to match the k8s version, and it works on GKE. @kkimdev can you try it out on your K8s install?

**Comment by kkimdev** [comment]
It worked well on both gke and  kubeadm-dind-cluster.  Thanks!
