### ISSUE TITLE
TidbClusters are synced too frequently even if there is no update to it

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3080]
## Feature Request

**Is your feature request related to a problem? Please describe:**

By default, the resync duration for the CRs are 30s, however, currently, the TidbClusters are synced very frequently even if no update to them.
**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by DanielZhangQD** [comment]
```
I0806 01:01:28.468298       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:01:40.670287       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:01:54.069548       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:02:02.666732       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:02:13.867462       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:02:25.866712       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:02:39.467229       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:02:50.068625       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:02:59.467018       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:03:10.266458       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:03:23.869315       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
I0806 01:03:35.267130       1 tidbcluster_control.go:66] TidbCluster: [ns1/ns1] updated successfully
```

**Comment by dragonly** [comment]
I also observed this issue by apply https://github.com/pingcap/tidb-operator/blob/master/examples/advanced/tidb-cluster.yaml
It seems there's another problem: the operator starts to sync tikv after pd is ready for about 20s.
the requeuing log is as follows:
```
➜  ~/pingcap/tidb-operator/tidb-operator git:(e2e-improve-semantics) ✗ kubectl logs pod/tidb-controller-manager-69548c7756-vx46h --namespace=pingcap --container=tidb-operator -f | grep requeuing
I0106 06:56:48.736255       1 tidb_cluster_controller.go:121] TidbCluster: default/advanced-tidb, still need sync: TidbCluster: [default/advanced-tidb], waiting for PD cluster running, requeuing
E0106 06:56:49.891995       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:56:50.996938       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:56:52.098529       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:56:52.184192       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:56:52.255444       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:56:52.334331       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:56:52.724084       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:56:53.171758       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:56:53.759805       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:56:59.026557       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:56:59.105174       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
E0106 06:57:04.287834       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed TidbCluster: default/advanced-tidb's pd status sync failed, can't failover, requeuing
I0106 06:57:23.486267       1 tidb_cluster_controller.go:121] TidbCluster: default/advanced-tidb, still need sync: TidbCluster: [default/advanced-tidb], waiting for TiKV cluster running, requeuing
I0106 06:57:24.857548       1 tidb_cluster_controller.go:121] TidbCluster: default/advanced-tidb, still need sync: TidbCluster: [default/advanced-tidb], waiting for TiKV cluster running, requeuing
I0106 06:57:25.028463       1 tidb_cluster_controller.go:121] TidbCluster: default/advanced-tidb, still need sync: TidbCluster: [default/advanced-tidb], waiting for TiKV cluster running, requeuing
I0106 06:57:25.220036       1 tidb_cluster_controller.go:121] TidbCluster: default/advanced-tidb, still need sync: TidbCluster: [default/advanced-tidb], waiting for TiKV cluster running, requeuing
I0106 06:57:26.019865       1 tidb_cluster_controller.go:121] TidbCluster: default/advanced-tidb, still need sync: TidbCluster: [default/advanced-tidb], waiting for TiKV cluster running, requeuing
I0106 06:57:26.817836       1 tidb_cluster_controller.go:121] TidbCluster: default/advanced-tidb, still need sync: TidbCluster: [default/advanced-tidb], waiting for TiKV cluster running, requeuing
I0106 06:57:27.642390       1 tidb_cluster_controller.go:121] TidbCluster: default/advanced-tidb, still need sync: TidbCluster: [default/advanced-tidb], waiting for TiKV cluster running, requeuing
I0106 06:57:28.418418       1 tidb_cluster_controller.go:121] TidbCluster: default/advanced-tidb, still need sync: TidbCluster: [default/advanced-tidb], waiting for TiKV cluster running, requeuing
E0106 06:57:56.075501       1 tidb_cluster_controller.go:123] TidbCluster: default/advanced-tidb, sync failed context deadline exceeded, requeuing
```

**Comment by songjiansuper** [comment]
more log for this problem,It seems that it should belong to the same problem, all caused by resync
    
I0326 07:58:34.947824       1 reflector.go:241] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: forcing resync
I0326 07:58:34.959892       1 reflector.go:241] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: forcing resync
I0326 07:58:34.960011       1 backup_controller.go:157] backup tidb-sj3/demo1-backup-s3 is Complete, skipping.
I0326 07:58:34.960022       1 reflector.go:241] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: forcing resync
I0326 07:58:34.962176       1 round_trippers.go:443] POST https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/roles 409 Conflict in 13 milliseconds
I0326 07:58:34.962231       1 reflector.go:241] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: forcing resync
I0326 07:58:34.962260       1 reflector.go:241] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: forcing resync
I0326 07:58:34.966885       1 round_trippers.go:443] GET https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/roles/basic-discovery 200 OK in 4 milliseconds
I0326 07:58:34.968123       1 reflector.go:241] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: forcing resync
I0326 07:58:34.968192       1 restore_controller.go:149] restore tidb-sj3/demo2-restore-s3 is Complete, skipping.
I0326 07:58:34.977499       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/serviceaccounts 409 Conflict in 10 milliseconds
I0326 07:58:34.981811       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/serviceaccounts/basic-discovery 200 OK in 4 milliseconds
I0326 07:58:35.006712       1 round_trippers.go:443] POST https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/rolebindings 409 Conflict in 24 milliseconds
I0326 07:58:35.009969       1 round_trippers.go:443] GET https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/rolebindings/basic-discovery 200 OK in 3 milliseconds
I0326 07:58:35.018184       1 round_trippers.go:443] POST https://****:443/apis/apps/v1/namespaces/tidb-sj6/deployments 409 Conflict in 7 milliseconds
I0326 07:58:35.021400       1 round_trippers.go:443] GET https://****:443/apis/apps/v1/namespaces/tidb-sj6/deployments/basic-discovery 200 OK in 3 milliseconds
I0326 07:58:35.026863       1 round_trippers.go:443] PUT https://****:443/apis/apps/v1/namespaces/tidb-sj6/deployments/basic-discovery 200 OK in 4 milliseconds
I0326 07:58:35.050148       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/services 409 Conflict in 22 milliseconds
I0326 07:58:35.054142       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/services/basic-discovery 200 OK in 3 milliseconds
I0326 07:58:35.077423       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 9 milliseconds
I0326 07:58:35.081333       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-pd-6130373 200 OK in 3 milliseconds
I0326 07:58:35.094719       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 9 milliseconds
I0326 07:58:35.100270       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tikv-3132336 200 OK in 5 milliseconds
I0326 07:58:35.106972       1 tidb_member_manager.go:338] get tidb in use config map name: basic-tidb-6462366
I0326 07:58:35.117091       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 9 milliseconds
I0326 07:58:35.120595       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tidb-6462366 200 OK in 3 milliseconds
I0326 07:58:35.135222       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 8 milliseconds
I0326 07:58:35.138626       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tiflash-3662356 200 OK in 3 milliseconds
I0326 07:58:35.142716       1 pod_control.go:171] pod tidb-sj6/basic-pd-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:35.142753       1 pvc_control.go:151] pvc tidb-sj6/pd-basic-pd-0 already has labels and annotations synced, skipping, : basic
I0326 07:58:35.142775       1 pv_control.go:131] pv pvc-b70f1a26-7638-4d8d-afa4-1c0d65e49324 already has labels and annotations synced, skipping. : tidb-sj6/basic
I0326 07:58:35.142783       1 pod_control.go:171] pod tidb-sj6/basic-tikv-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:35.142793       1 pvc_control.go:151] pvc tidb-sj6/tikv-basic-tikv-0 already has labels and annotations synced, skipping, : basic
I0326 07:58:35.142800       1 pv_control.go:131] pv pvc-031148e0-0b1c-4994-a52c-50f54e9c442c already has labels and annotations synced, skipping. : tidb-sj6/basic
I0326 07:58:35.142805       1 pod_control.go:171] pod tidb-sj6/basic-tidb-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:35.142810       1 pod_control.go:171] pod tidb-sj6/basic-discovery-59994cfdb-6zhfn already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:35.142814       1 pod_control.go:171] pod tidb-sj6/basic-tidb-1 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:35.142819       1 pod_control.go:171] pod tidb-sj6/basic-tiflash-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:35.142825       1 pvc_control.go:151] pvc tidb-sj6/data0-basic-tiflash-0 already has labels and annotations synced, skipping, : basic
I0326 07:58:35.142836       1 pv_control.go:131] pv pvc-eec837cf-c896-48dc-9da0-e2d0a4744a3c already has labels and annotations synced, skipping. : tidb-sj6/basic
I0326 07:58:35.142880       1 pvc_cleaner.go:231] cluster tidb-sj6/basic pvc pd-basic-pd-0 has not pod scheduling annotation, skip clean
I0326 07:58:35.142888       1 pvc_cleaner.go:231] cluster tidb-sj6/basic pvc tikv-basic-tikv-0 has not pod scheduling annotation, skip clean
I0326 07:58:35.142892       1 pvc_cleaner.go:231] cluster tidb-sj6/basic pvc data0-basic-tiflash-0 has not pod scheduling annotation, skip clean
I0326 07:58:35.142946       1 pvc_resizer.go:180] PVC tidb-sj6/pd-basic-pd-0 storage request is already 10Gi, skipped
I0326 07:58:35.142964       1 pvc_resizer.go:180] PVC tidb-sj6/tikv-basic-tikv-0 storage request is already 10Gi, skipped
I0326 07:58:35.142979       1 pvc_resizer.go:180] PVC tidb-sj6/data0-basic-tiflash-0 storage request is already 1Gi, skipped
I0326 07:58:35.147031       1 tidbcluster_status_manager.go:131] tc[tidb-sj6/basic] autoscaler is empty
I0326 07:58:35.161209       1 round_trippers.go:443] PUT https://****:443/apis/pingcap.com/v1alpha1/namespaces/tidb-sj6/tidbclusters/basic 200 OK in 13 milliseconds
I0326 07:58:35.161899       1 tidbcluster_control.go:66] TidbCluster: [tidb-sj6/basic] updated successfully
I0326 07:58:35.161919       1 tidb_cluster_controller.go:139] Finished syncing TidbCluster "tidb-sj6/basic" (213.958248ms)
I0326 07:58:35.171982       1 round_trippers.go:443] POST https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/roles 409 Conflict in 7 milliseconds
I0326 07:58:35.175766       1 round_trippers.go:443] GET https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/roles/basic-discovery 200 OK in 3 milliseconds
I0326 07:58:35.182441       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/serviceaccounts 409 Conflict in 6 milliseconds
I0326 07:58:35.186486       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/serviceaccounts/basic-discovery 200 OK in 3 milliseconds
I0326 07:58:35.211470       1 round_trippers.go:443] POST https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/rolebindings 409 Conflict in 24 milliseconds
I0326 07:58:35.215155       1 round_trippers.go:443] GET https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/rolebindings/basic-discovery 200 OK in 3 milliseconds
I0326 07:58:35.223160       1 round_trippers.go:443] POST https://****:443/apis/apps/v1/namespaces/tidb-sj6/deployments 409 Conflict in 7 milliseconds
I0326 07:58:35.229156       1 round_trippers.go:443] GET https://****:443/apis/apps/v1/namespaces/tidb-sj6/deployments/basic-discovery 200 OK in 4 milliseconds
I0326 07:58:35.235257       1 round_trippers.go:443] PUT https://****:443/apis/apps/v1/namespaces/tidb-sj6/deployments/basic-discovery 200 OK in 5 milliseconds
I0326 07:58:35.257371       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/services 409 Conflict in 21 milliseconds
I0326 07:58:35.261183       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/services/basic-discovery 200 OK in 3 milliseconds
I0326 07:58:35.281835       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 8 milliseconds
I0326 07:58:35.285856       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-pd-6130373 200 OK in 3 milliseconds
I0326 07:58:35.300055       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 10 milliseconds
I0326 07:58:35.467789       1 request.go:538] Throttling request took 167.562262ms, request: GET:https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tikv-3132336
I0326 07:58:35.472146       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tikv-3132336 200 OK in 4 milliseconds
I0326 07:58:35.479100       1 tidb_member_manager.go:338] get tidb in use config map name: basic-tidb-6462366
I0326 07:58:35.609696       1 reflector.go:241] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: forcing resync
I0326 07:58:35.609696       1 reflector.go:241] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: forcing resync
I0326 07:58:35.667759       1 request.go:538] Throttling request took 188.468954ms, request: POST:https://****:443/api/v1/namespaces/tidb-sj6/configmaps
I0326 07:58:35.677481       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 9 milliseconds
I0326 07:58:35.795854       1 reflector.go:241] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: forcing resync
I0326 07:58:35.796090       1 controller_utils.go:440] controller tidb-sj6/basic of tidb-sj6/basic-discovery not found, ignore
I0326 07:58:35.867766       1 request.go:538] Throttling request took 190.135967ms, request: GET:https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tidb-6462366
I0326 07:58:35.873028       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tidb-6462366 200 OK in 5 milliseconds
I0326 07:58:36.067759       1 request.go:538] Throttling request took 188.058378ms, request: POST:https://****:443/api/v1/namespaces/tidb-sj6/configmaps
I0326 07:58:36.077598       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 9 milliseconds
I0326 07:58:36.267770       1 request.go:538] Throttling request took 190.021828ms, request: GET:https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tiflash-3662356
I0326 07:58:36.272198       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tiflash-3662356 200 OK in 4 milliseconds
I0326 07:58:36.276849       1 pod_control.go:171] pod tidb-sj6/basic-tiflash-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:36.276873       1 pvc_control.go:151] pvc tidb-sj6/data0-basic-tiflash-0 already has labels and annotations synced, skipping, : basic
I0326 07:58:36.276882       1 pv_control.go:131] pv pvc-eec837cf-c896-48dc-9da0-e2d0a4744a3c already has labels and annotations synced, skipping. : tidb-sj6/basic
I0326 07:58:36.276888       1 pod_control.go:171] pod tidb-sj6/basic-discovery-59994cfdb-6zhfn already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:36.276893       1 pod_control.go:171] pod tidb-sj6/basic-tidb-1 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:36.276897       1 pod_control.go:171] pod tidb-sj6/basic-tidb-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:36.276902       1 pod_control.go:171] pod tidb-sj6/basic-pd-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:36.276908       1 pvc_control.go:151] pvc tidb-sj6/pd-basic-pd-0 already has labels and annotations synced, skipping, : basic
I0326 07:58:36.276915       1 pv_control.go:131] pv pvc-b70f1a26-7638-4d8d-afa4-1c0d65e49324 already has labels and annotations synced, skipping. : tidb-sj6/basic
I0326 07:58:36.276919       1 pod_control.go:171] pod tidb-sj6/basic-tikv-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:36.276926       1 pvc_control.go:151] pvc tidb-sj6/tikv-basic-tikv-0 already has labels and annotations synced, skipping, : basic
I0326 07:58:36.276932       1 pv_control.go:131] pv pvc-031148e0-0b1c-4994-a52c-50f54e9c442c already has labels and annotations synced, skipping. : tidb-sj6/basic
I0326 07:58:36.276958       1 pvc_cleaner.go:231] cluster tidb-sj6/basic pvc pd-basic-pd-0 has not pod scheduling annotation, skip clean
I0326 07:58:36.276964       1 pvc_cleaner.go:231] cluster tidb-sj6/basic pvc tikv-basic-tikv-0 has not pod scheduling annotation, skip clean
I0326 07:58:36.276968       1 pvc_cleaner.go:231] cluster tidb-sj6/basic pvc data0-basic-tiflash-0 has not pod scheduling annotation, skip clean
I0326 07:58:36.277003       1 pvc_resizer.go:180] PVC tidb-sj6/pd-basic-pd-0 storage request is already 10Gi, skipped
I0326 07:58:36.277017       1 pvc_resizer.go:180] PVC tidb-sj6/tikv-basic-tikv-0 storage request is already 10Gi, skipped
I0326 07:58:36.277035       1 pvc_resizer.go:180] PVC tidb-sj6/data0-basic-tiflash-0 storage request is already 1Gi, skipped
I0326 07:58:36.280447       1 tidbcluster_status_manager.go:131] tc[tidb-sj6/basic] autoscaler is empty
I0326 07:58:36.295303       1 round_trippers.go:443] PUT https://****:443/apis/pingcap.com/v1alpha1/namespaces/tidb-sj6/tidbclusters/basic 200 OK in 14 milliseconds
I0326 07:58:36.295835       1 tidbcluster_control.go:66] TidbCluster: [tidb-sj6/basic] updated successfully
I0326 07:58:36.295849       1 tidb_cluster_controller.go:139] Finished syncing TidbCluster "tidb-sj6/basic" (1.131566318s)
I0326 07:58:36.308854       1 round_trippers.go:443] POST https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/roles 409 Conflict in 9 milliseconds
I0326 07:58:36.314403       1 round_trippers.go:443] GET https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/roles/basic-discovery 200 OK in 5 milliseconds
I0326 07:58:36.323453       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/serviceaccounts 409 Conflict in 8 milliseconds
I0326 07:58:36.327804       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/serviceaccounts/basic-discovery 200 OK in 4 milliseconds
I0326 07:58:36.350761       1 round_trippers.go:443] POST https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/rolebindings 409 Conflict in 22 milliseconds
I0326 07:58:36.354793       1 round_trippers.go:443] GET https://****:443/apis/rbac.authorization.k8s.io/v1/namespaces/tidb-sj6/rolebindings/basic-discovery 200 OK in 3 milliseconds
I0326 07:58:36.362456       1 round_trippers.go:443] POST https://****:443/apis/apps/v1/namespaces/tidb-sj6/deployments 409 Conflict in 7 milliseconds
I0326 07:58:36.366686       1 round_trippers.go:443] GET https://****:443/apis/apps/v1/namespaces/tidb-sj6/deployments/basic-discovery 200 OK in 4 milliseconds
I0326 07:58:36.372079       1 round_trippers.go:443] PUT https://****:443/apis/apps/v1/namespaces/tidb-sj6/deployments/basic-discovery 200 OK in 4 milliseconds
I0326 07:58:36.397584       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/services 409 Conflict in 25 milliseconds
I0326 07:58:36.401988       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/services/basic-discovery 200 OK in 4 milliseconds
I0326 07:58:36.467781       1 request.go:538] Throttling request took 53.715275ms, request: POST:https://****:443/api/v1/namespaces/tidb-sj6/configmaps
I0326 07:58:36.479638       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 11 milliseconds
I0326 07:58:36.667754       1 request.go:538] Throttling request took 187.970102ms, request: GET:https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-pd-6130373
I0326 07:58:36.673060       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-pd-6130373 200 OK in 5 milliseconds
I0326 07:58:36.867758       1 request.go:538] Throttling request took 190.937759ms, request: POST:https://****:443/api/v1/namespaces/tidb-sj6/configmaps
I0326 07:58:36.880025       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 12 milliseconds
I0326 07:58:37.067785       1 request.go:538] Throttling request took 187.603684ms, request: GET:https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tikv-3132336
I0326 07:58:37.072852       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tikv-3132336 200 OK in 4 milliseconds
I0326 07:58:37.079552       1 tidb_member_manager.go:338] get tidb in use config map name: basic-tidb-6462366
I0326 07:58:37.191841       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-admin/endpoints/tidb-controller-manager 200 OK in 4 milliseconds
I0326 07:58:37.198873       1 round_trippers.go:443] PUT https://****:443/api/v1/namespaces/tidb-admin/endpoints/tidb-controller-manager 200 OK in 6 milliseconds
I0326 07:58:37.198982       1 leaderelection.go:282] successfully renewed lease tidb-admin/tidb-controller-manager
I0326 07:58:37.267779       1 request.go:538] Throttling request took 188.031719ms, request: POST:https://****:443/api/v1/namespaces/tidb-sj6/configmaps
I0326 07:58:37.280596       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 12 milliseconds
I0326 07:58:37.467761       1 request.go:538] Throttling request took 187.026025ms, request: GET:https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tidb-6462366
I0326 07:58:37.472414       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tidb-6462366 200 OK in 4 milliseconds
I0326 07:58:37.667762       1 request.go:538] Throttling request took 189.18459ms, request: POST:https://****:443/api/v1/namespaces/tidb-sj6/configmaps
I0326 07:58:37.681128       1 round_trippers.go:443] POST https://****:443/api/v1/namespaces/tidb-sj6/configmaps 409 Conflict in 13 milliseconds
I0326 07:58:37.867759       1 request.go:538] Throttling request took 186.464282ms, request: GET:https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tiflash-3662356
I0326 07:58:37.873249       1 round_trippers.go:443] GET https://****:443/api/v1/namespaces/tidb-sj6/configmaps/basic-tiflash-3662356 200 OK in 5 milliseconds
I0326 07:58:37.877735       1 pod_control.go:171] pod tidb-sj6/basic-tidb-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:37.877749       1 pod_control.go:171] pod tidb-sj6/basic-pd-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:37.877761       1 pvc_control.go:151] pvc tidb-sj6/pd-basic-pd-0 already has labels and annotations synced, skipping, : basic
I0326 07:58:37.877771       1 pv_control.go:131] pv pvc-b70f1a26-7638-4d8d-afa4-1c0d65e49324 already has labels and annotations synced, skipping. : tidb-sj6/basic
I0326 07:58:37.877776       1 pod_control.go:171] pod tidb-sj6/basic-tikv-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:37.877783       1 pvc_control.go:151] pvc tidb-sj6/tikv-basic-tikv-0 already has labels and annotations synced, skipping, : basic
I0326 07:58:37.877792       1 pv_control.go:131] pv pvc-031148e0-0b1c-4994-a52c-50f54e9c442c already has labels and annotations synced, skipping. : tidb-sj6/basic
I0326 07:58:37.877797       1 pod_control.go:171] pod tidb-sj6/basic-tiflash-0 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:37.877804       1 pvc_control.go:151] pvc tidb-sj6/data0-basic-tiflash-0 already has labels and annotations synced, skipping, : basic
I0326 07:58:37.877817       1 pv_control.go:131] pv pvc-eec837cf-c896-48dc-9da0-e2d0a4744a3c already has labels and annotations synced, skipping. : tidb-sj6/basic
I0326 07:58:37.877822       1 pod_control.go:171] pod tidb-sj6/basic-discovery-59994cfdb-6zhfn already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:37.877829       1 pod_control.go:171] pod tidb-sj6/basic-tidb-1 already has cluster labels set, skipping. TidbCluster: basic
I0326 07:58:37.877851       1 pvc_cleaner.go:231] cluster tidb-sj6/basic pvc pd-basic-pd-0 has not pod scheduling annotation, skip clean
I0326 07:58:37.877859       1 pvc_cleaner.go:231] cluster tidb-sj6/basic pvc tikv-basic-tikv-0 has not pod scheduling annotation, skip clean
I0326 07:58:37.877863       1 pvc_cleaner.go:231] cluster tidb-sj6/basic pvc data0-basic-tiflash-0 has not pod scheduling annotation, skip clean
I0326 07:58:37.877899       1 pvc_resizer.go:180] PVC tidb-sj6/pd-basic-pd-0 storage request is already 10Gi, skipped
I0326 07:58:37.877911       1 pvc_resizer.go:180] PVC tidb-sj6/tikv-basic-tikv-0 storage request is already 10Gi, skipped
I0326 07:58:37.877925       1 pvc_resizer.go:180] PVC tidb-sj6/data0-basic-tiflash-0 storage request is already 1Gi, skipped
I0326 07:58:37.881379       1 tidbcluster_status_manager.go:131] tc[tidb-sj6/basic] autoscaler is empty
I0326 07:58:37.894519       1 round_trippers.go:443] PUT https://****:443/apis/pingcap.com/v1alpha1/namespaces/tidb-sj6/tidbclusters/basic 200 OK in 12 milliseconds
I0326 07:58:37.894986       1 tidbcluster_control.go:66] TidbCluster: [tidb-sj6/basic] updated successfully
I0326 07:58:37.895000       1 tidb_cluster_controller.go:139] Finished syncing TidbCluster "tidb-sj6/basic" (1.595623259s)

**Comment by songjiansuper** [comment]
I compared the content under metadata:annotations:kubectl.kubernetes.io/last-applied-configuration, and this has not changed. I suspect this may be caused by the heartbeat in the status.
