### ISSUE TITLE
Tidb-scheduler fails to schedule recovered Pod.

### ISSUE THREAD

**Issue by cvvz** [pingcap/tidb-operator#3252]
## Bug Report

**What did you do?**

1. I modified the image of tikv to a wrong value, which cause ImagePullBackOff, and the tikv Pod is down for a while and triggers failover. 
2. A new tikv Pod is generated, but because of lack of resource, it is pending.
3. Correct the fault Pod's image, and it is back to normal, but the scheduler can't schedule it bucause of `serial scheduling`.

Here is tidb-scheduler's log:
```shell
I0909 17:19:41.723287       1 event.go:255] Event(v1.ObjectReference{Kind:"Pod", Namespace:"blade2", Name:"blade-blade-blade2tcpcopy-tikv-2", UID:"08839255-279c-4463-8bf7-fe2388d34f4e", APIVersion:"v1", ResourceVersion:"150795445", FieldPath:""}): type: 'Warning' reason: 'HAScheduling' waiting for Pod blade2/blade-blade-blade2tcpcopy-tikv-3 scheduling

```

**What did you expect to see?**
New generated Pod don't block schedule process of recovered Pod.

**Comment by DanielZhangQD** [comment]
@cvvz The Pod recovered from failure will never get scheduled?

**Comment by cvvz** [comment]
@DanielZhangQD In the situation I memtioned, yes.

**Comment by DanielZhangQD** [comment]
cc @weekface @july2993

**Comment by DanielZhangQD** [comment]
Root Cause:
The scheduling for the same component in the same TiDB Cluster is done serially to achieve the HA topology mentioned in this [doc](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/tidb-scheduler).
When a pod is to be scheduled, tidb-scheduler will add `tidb.pingcap.com/pod-scheduling` annotation to its PVC as a lock to indicate that this Pod is being scheduled so that the other pods of the same component in the same TiDB Cluster cannot be scheduled at the same time. (Code: [Filter](https://github.com/pingcap/tidb-operator/blob/master/pkg/scheduler/predicates/ha.go#L82) -> [acquireLockFn](https://github.com/pingcap/tidb-operator/blob/master/pkg/scheduler/predicates/ha.go#L99) -> [realAcquireLock](https://github.com/pingcap/tidb-operator/blob/master/pkg/scheduler/predicates/ha.go#L271))
When the Pod is scheduled, the annotation in the PVC will be cleaned by the PVC cleaner [here](https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/pvc_cleaner.go#L81).
However, if one Pod cannot be scheduled, e.g. by the HA policy, it will block the scheduling of other Pods.

Solution:
When we add the `tidb.pingcap.com/pod-scheduling` annotation to the PVC, we can also add a timeout Annotation, e.g. `tidb.pingcap.com/pod-scheduling-timeout: now()+60s`, the `60s` is just an example here.
Then in the PVC cleaner [here](https://github.com/pingcap/tidb-operator/blob/master/pkg/manager/member/pvc_cleaner.go#L274) we can check the timeout annotation and delete both of the annotations if the Pod is not scheduled before timeout.

cc @cvvz @july2993

**Comment by cvvz** [comment]
This issue have been solved by https://github.com/pingcap/tidb-operator/pull/3419 in a different way.
