### ISSUE TITLE
Supports search log with TiDB Dashboard

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb-operator#3416]
## Feature Request

**Is your feature request related to a problem? Please describe:**

the cluster that deployed by the operator cannot use the dashboard to search the cluster logs. if it supported, it can improve our efficiency in troubleshooting.
**Describe the feature you'd like:**

Supports search log with dashboard

**Describe alternatives you've considered:**

- maybe the stdout still need to output.

**Teachability, Documentation, Adoption, Migration Strategy:**

- Go

**Comment by mikechengwei** [comment]
We can use loki to integrate into grafana.

**Comment by DanielZhangQD** [comment]
> We can use loki to integrate into grafana.

@mikechengwei You mean deploy loki and integrate to the Grafana of the cluster monitoring？
Could you please share any link for the solution?

**Comment by nolouch** [comment]
If it supported in the TiDB dashboard, we do not need to maintain other components.

**Comment by mikechengwei** [comment]
This proposal has been rejected in advance, we can use Loki to store log data, Promtail as a sidecar to collect logs, and grafana shows.

**Comment by DanielZhangQD** [comment]
> If it supported in the TiDB dashboard, we do not need to maintain other components.

@nolouch In Kubernetes, the best practice to collect logs is to use solutions such as EFK/ELK/Loki+Grafana to collect the logs from the stdout/stderr of containers.
If we're going to support log searching in the TiDB Dashboard, we have the following ways:
1. Print logs to both disks and stdout/stderr.
    Additional disks are required, duplicate logs and meaningless, if users are running apps on Kubernetes, they usually are familiar with the solutions on Kubernetes, why do they bother to go to Dashboard to check logs?
2. TiDB Dashboard supports retrieving logs from the EFK/ELK/Loki+Grafana solutions.
    This is really not necessary, requires great effort, and I do not think TiDB Dashboard can do better than the Kibana and Grafana as a UI for log operations.

**Comment by XiaoGe2030** [comment]
> the best practice to collect logs is to use solutions such as EFK/ELK/Loki+Grafana to collect the logs from the stdout/stderr of containers

Has tidb implemented EFK/ELK/Loki + grafana solutions ? Where can I get the original file of slow log?

**Comment by Yisaer** [comment]
I think after https://github.com/pingcap/tidb-operator/pull/3444 merged, the tidb-dashboard could search log if the pd/tikv/tidb configure the logpath into mounted pvc path.

Moreover, I think searching log by TiDB Dashboard is necessary with native components for performance tuning and error detecting, so I marked this request as accepted.

**Comment by nolouch** [comment]
@DanielZhangQD  Dashboard also uses `logfile` to analyze slow log queries, I think we already run a `slow log` container to make it work. but in the future, more tools like this use logfile as an origin data may be integrated into the dashboard, such as cluster diagnostics.

**Comment by breeswish** [comment]
I prefer using Loki / ELK over TiDB Dashboard in this case, since these stacks like ELK is more powerful and easy to use.. The log search in TiDB Dashboard is only meant to be a simple implementation when ELK is not easy to be deployed.

However, for slow log, it's another story. Slow logs should be supported by TiDB Dashboard natively, since TiDB Dashboard provides nice interpretation while ELK is not good at it.

**Comment by DanielZhangQD** [comment]
> However, for slow log, it's another story. Slow logs should be supported by TiDB Dashboard natively, since TiDB Dashboard provides nice interpretation while ELK is not good at it.

Agree. BTW, the slow log is printed to the disk now, do you see any issues with the slow log functions in the TiDB Dashboard? @breeswish @nolouch

**Comment by breeswish** [comment]
> > However, for slow log, it's another story. Slow logs should be supported by TiDB Dashboard natively, since TiDB Dashboard provides nice interpretation while ELK is not good at it.
> 
> Agree. BTW, the slow log is printed to the disk now, do you see any issues with the slow log functions in the TiDB Dashboard? @breeswish @nolouch

I think there is no issue for slow log.

Maybe we can encourage users to deploy ELK in K8S, to make troubleshooting easier :)

**Comment by nolouch** [comment]
@breeswish  What should I do if there are requirements similar to the slow query in the subsequent Dashboard? For example, if I want to analyze the scheduling behavior in the past period of time through logs.

**Comment by breeswish** [comment]
> @breeswish What should I do if there are requirements similar to the slow query in the Dashboard? For example, if I want to analyze the scheduling behavior in the past period of time through logs.

How about writing standalone & structural logs (or any kind of things that can be easily accessed by programs, e.g. just provide in-memory structural data), and then make it available in TiDB Dashboard?

Notice that UI features in TiDB Dashboard are mostly targeted at DBAs. If the purpose is to easily analyze some scheduling bugs by our developers instead of users (DBAs), then it may stay inside "advanced" menu if a UI really make this diagnostics simpler.

**Comment by DanielZhangQD** [comment]
PD & TiKV & TiDB have supported mounting multiple volumes from v1.1.7, users can configure the components to print logs to disk as they do in non-k8s env, then everything should work well with TiDB Dashboard. However, there will be no logs in the stdout/stderr of the containers, let's wait for feedback from users.

**Comment by breeswish** [comment]
Considering our cloud first strategy maybe for normal logs we'd better stick in a direction that is more cloud native, e.g. better ELK ecology friendly instead of building our own powerful log search engine. So that I think this issue can be closed, while some other issues can be opened, like:

- Support ELK to search logs in cloud native deployments for TiDB Dashboard (in TiDB Dashboard repo)

What do you think? @nolouch

**Comment by nolouch** [comment]
lgtm
