### ISSUE TITLE
autoFailover leaves pod in error state

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb-operator#408]
Steps to reproduce:
1) install operator with autoFailover=true and a cluster
2) gcloud compute instances delete <tikv-node>

Actual behavior:
The same number of pods exist (3). The pod that loses its node is re-scheduled to a new node. However, it continually fails with a duplicated store error: 

```
2019/04/17 23:11:08.233 ERRO util.rs:336: fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:64 address:\"demo-tikv-1.demo-tikv-peer.tidb120002.svc:20160\" version:\"2.1.3\" , already registered by id:4 address:\"demo-tikv-1.demo-tikv-peer.tidb120002.svc:20160\" ...
```

So the capacity of TiKV is now 2.

Expected behavior:
* There should be 3 TiKV pods that run without error

**Comment by tennix** [comment]
The expected behavior is there will be a pending pod and a new pod. That's 4 tikv pods.

**Comment by tennix** [comment]
The deleted node came back again with the same PV, but data in the PV was lost. So the tikv pod is scheduled to the node again with the PV. This causes tikv to print that error message.

**Comment by cofyc** [comment]
> The deleted node came back again with the same PV, but data in the PV was lost. So the tikv pod is scheduled to the node again with the PV. This causes tikv to print that error message.

Yes, this is what happened. There is one issue we need to fix and one situation we can improve:

1) First, we need to use the unique path of volume in PV object to prevent using new volume (e.g. newly created when the node gets recreated) with old PV object which is referenced by existing Pod.

Currently, we use [`--local-ssd-count` to create node pools](https://github.com/pingcap/dbaas/blob/master/operations/scaler/gke/autoscale.go#L239) which will mount local SSDs at non-unique paths (e.g. `/mnt/disks/ssd0`, `/mnt/disks/ssd1`). PV objects will have `/mnt/disks/ssdX` in its `spec.path` field.

But when nodes get recreated, local SSDs will be recreated and mounted at the same paths (note: autoDelete cannot be set to false for local SSD, `--keep-disks` cannot be used to keep local SSDs). 

But the underlying volume of local PV object is deleted, pods which use old volume data should not start with another volume data (empty here).

We can use [`--local-ssd-volumes` flag](https://cloud.google.com/sdk/gcloud/reference/alpha/container/node-pools/create) to name the device/mount point with a UUID in the name instead of the non-unique name (e.g. `/mnt/disks/ssd0`). With a unique path in local PV, when nodes get recreated, pods using old volumes will fail to start. This is expected behavior because the volume has been deleted by deleting the nodes.

`--local-ssd-volumes` flag is alpha for now but will be beta soon.

2) Second, clean up stale local PVs of which underlying volumes are missing

There are many possibilities that underlying volume of PV object is missing on the node, for safety, provisioner will not delete PV object if it fails to clean up the volume. The prevents the old volume from being used by other programs if it recovers later.

But if we have a reliable mechanism the detect the underlying volume is permanently deleted, we can delete the PV object (in practice, we need to set an annotation to distinguish it from deletion by accident). When local PVs used by `tidb-kv` are going to be deleted (`metadata.deletionTimestamp` will be non-nil, and only be deleted from API server when PVCs are deleted because of pv-protection finalizer), tidb-operator can clean up failed pod because local PVs are impossible to recover.

**Comment by cofyc** [comment]
For the second, maybe we can add a small sidecar (perhaps gke-specific) to do this task. This is [under investigation](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/issues/78).

**Comment by weekface** [comment]
@gregwebs @cofyc what is the status of this issue?

**Comment by gregwebs** [comment]
I can re-test this scenario next week.

**Comment by gregwebs** [comment]
Now that I mount by UUID the pod gets stuck in the `Init` phase.

```
  Warning  FailedMount        118s                   kubelet, gke-alpha-tidb-n1-standard-2-375-1a551ee1-q09m  Unable to mount volumes for pod "demo-tikv-1_tidb30030(d2d2c43a-b209-11e9-9725-4201ac1f400a)": timeout expired waiting for volumes to attach or mount for pod "tidb30030"/"demo-tikv-1". list of unmounted volumes=[tikv]. list of unattached volumes=[tikv annotations config startup-script default-token-kk6b4]
  Warning  FailedMount        115s (x9 over 4m3s)    kubelet, gke-alpha-tidb-n1-standard-2-375-1a551ee1-q09m  MountVolume.NewMounter initialization failed for volume "local-pv-27c5592a" : path "/mnt/disks/3fbcd839-7206-4657-96e2-77c124263a5b" does not exist
```

**Comment by gregwebs** [comment]
This seems much better because the error that we get is now showing exactly what the issue is.

At first glance I am not sure what we can do to ensure reliability in this case. GKE is trying to provide an abstraction stating that these nodes are the same, but they are not since the disk is now different. However, I do notice that when describing the pod the Node field also gives the IP address.

```
Node:           gke-alpha-tidb-n1-standard-2-375-1a551ee1-q09m/172.31.252.49
```

But I don't know if we can rely on the IP address changing. It seems possible that the internal IP address could end up getting re-used when the node comes back.

**Comment by gregwebs** [comment]
@cofyc this seems like a GKE bug to me that they are re-using a Kubernetes node for different instance. What do you think?

**Comment by gregwebs** [comment]
`container.googleapis.com/instance_id` and `uid` change when the node comes back.
Perhaps the issue is that K8s [should be using the node uid](https://github.com/kubernetes/kubernetes/issues/39893) rather than nodename?

It is [suggested that local-volume-provisioner should default to using the nodename rather than the uid](https://github.com/pingcap/tidb-operator/issues/421#event-2485223986), but this seems like a reason to not change the default for that setting.

**Comment by cofyc** [comment]
@gregwebs You're right, the node object is no longer recreated on upgrade/repair even though the underlying instance is still recreated (and local SSDs are wiped), see discussion [here](https://github.com/kubernetes-incubator/external-storage/issues/945#issuecomment-414393266). 

In this case, we should clean up stale local PV objects when the underlying disks are gone.

**Comment by cofyc** [comment]
BTW, `container.googleapis.com/instance_id` and `uid` are the attributes of the GKE node or Kubernetes node object?

**Comment by cofyc** [comment]
> @cofyc this seems like a GKE bug to me that they are re-using a Kubernetes node for different instance. What do you think?

I guess it's the expected behavior in GKE.

**Comment by gregwebs** [comment]
> BTW, container.googleapis.com/instance_id and uid are the attributes of the GKE node or Kubernetes node object?

I am only looking at the K8s node object

**Comment by gregwebs** [comment]
> In GKE, I guess we can try to unbind the PVC/PV and delete the pod if we are sure the machine is different (and also delete the stale PVs with non-existing paths). When the pod got recreated with a new PVC, the scheduler will try to find a new PV and node for it.

Will some of this be done by the local-volume-provisioner?

**Comment by cofyc** [comment]
> > BTW, container.googleapis.com/instance_id and uid are the attributes of the GKE node or Kubernetes node object?
>
> I am only looking at the K8s node object
>
> > In GKE, I guess we can try to unbind the PVC/PV and delete the pod if we are sure the machine is different (and also delete the stale PVs with non-existing paths). When the pod got recreated with a new PVC, the scheduler will try to find a new PV and node for it.
>
> Will some of this be done by the local-volume-provisioner?
>

I think local-volume-provisioner should delete the stale PVs with non-existing paths and it's our controller's job to unbind the PVC/PV and delete the pod.

If the UID of the node object changes, so the node object is recreated. We can [set PVs owner references](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/123). When the node object is deleted, the K8S garbage collector will delete the PVs owned by this node. This will delete the stale PVs not owned by current nodes. This feature is merged recently. I'll tag a new version soon.

**Comment by gregwebs** [comment]
okay, let me know when there is a new release

**Comment by cofyc** [comment]
@gregwebs 
v2.3.3 has been released, https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/releases/tag/v2.3.3

`setPVOwnerRef: "true"`, xref: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/123/files

**Comment by gregwebs** [comment]
@cofyc great! What I see now is the PV shows up as state Terminating

```
local-pv-30e090e9                          368Gi      RWO            Retain           Terminating   tidb7/tikv-demo-tikv-2              local-storage
local-pv-eaea7843                          368Gi      RWO            Delete           Available                                         local-storage
```

Interestingly, if I patch the reclaim policy of the terminating PV to be "Delete", it will revert back to Retain.

Seeing the Terminating PV is promising, but it seems I need something more? The pod error message is still the same, and effectively the result is still the same

**Comment by cofyc** [comment]
> Interestingly, if I patch the reclaim policy of the terminating PV to be "Delete", it will revert back to Retain.

I think the revert is done by tidb-operator [here](https://github.com/pingcap/tidb-operator/blob/e52b0a2447046ce760c3153f7965f3dd7d8ba6dd/pkg/manager/meta/reclaim_policy_manager.go#L41).

When `setPVOwnerRef` is enabled, provisioned PVs are owned by the node object. When the node object is deleted, k8s garbage collector controller will try to delete the PVs (set the metadata.deletionTimestamp to current time). PVs have `kubernetes.io/pv-protection` finalizer now. If the PV is used by a PVC, it will not be deleted from the apiserver physically.

In this scenario, we can delete the error pod its PVC because we can check the cloud provider API that the node the pod is running on does not exist anymore. This step is manual operation in a bare-metal environment. However, in fully-managed cloud environment, we can do it better.

**Comment by gregwebs** [comment]
In my case, the K8s node name does exist. The underlying compute instance has changed, and the node uid has changed. So tidb-operator should delete the pod & PVC?

**Comment by gregwebs** [comment]
I think that in this case (node uid change) it would be possible for local-volume-provisioner itself to delete the pod & PVC if the pod has replication: true (this could also be something turned on by a configuration setting)

**Comment by gregwebs** [comment]
I think better is to annotate the PVC and Pod so that a PV deletion will cascade up.

**Comment by cofyc** [comment]
> In my case, the K8s node name does exist. The underlying compute instance has changed, and the node uid has changed.

But the node which owns the local storage PV does not exist. Is it possible to check against the cloud provider API with the node UID to confirm the node which hosts the local PV is really gone?

> So tidb-operator should delete the pod & PVC?

The problem is local-volume-provisioner and tidb-operator has no way to confirm the local storage on that node was **really** deleted or inaccessible. The node object can be deleted by accident and the pod is running normally.

In a bare-metal environment, before administrators to fix the pod in error state, they must confirm that the machine is inaccessible. They also have two choices: fix the machine and wait for it to recover or delete the pod and its PVC.

The controller which can safely delete the pod and its PVC must confirm the node was **really** inaccessible. It must be integrated with a platform API.

We can integrate tidb-operator with cloud provider API and even bare-metal IPMI to automate this process but for now, it is not safe.

**Comment by cofyc** [comment]
> For tidb-operator, however, instead of just having a pod that is stuck creating, I think our behavior should be to create a new pod that does get scheduled. Once the replication factor is back to 3, we can then delete the troubled pod.

Yes, this is what we expected.

IIUC, the workflow will be like this:

- 1 When the node is gone, the pod on it will fail because the local PV is gone (https://github.com/pingcap/tidb-operator/issues/408#issuecomment-516008578)
  - if PVs are owned by the node, the PVs will be deleted
  - PVs bound with PVCs will not be physically deleted from the apiserver but will be in Terminating state (metadata.deletionTimestamp != nil)
- 2 tidb-operator waits 35 minutes by default to create a new TiKV pod if the autoFailover is enabled
  - In PD, when the downtime of the store exceeds `MaxStoreDownTime` (configurable via `max-store-down-time`, by default 30 minutes), the store will be marked as Down.
  - In tidb-operator, the TiKV manager will mark the store failed if the state of the store is Down and lasts 5 minutes (configurable via `--tikv-failover-period` flag). When the store is marked failed in the TiKV cluster, the TiKV manager will create a new replica for it.
- 3 When the new TiKV pod is synced, the replication factor is back to 3
  - Because available PVs owned by the deleted node will be garbaged collected, the new pod will get scheduled onto a node which is running
- We can delete pods on the deleted node (`.spec.nodeName == deletedNode.name`) and related PVCs when we confirm that the node cannot come back or the replication factor is back to 3, in which case it is safe to delete the troubled pod
  - when the PVCs are deleted, bound PVs will be physically deleted from the apiserver

**Comment by gregwebs** [comment]
2) 35 minutes + 5 minutes is an enormous amount of time. I am going to try out something closer to a minute.

I think that once the replication factor is back to 3 we don't need to worry about confirming whether the node can come back and we can just delete the troubled pod, particularly in the cloud or certain environment where we are not concerned about the new pod being placed on some certain node. So we can at least have an option to do this automatically.

**Comment by gregwebs** [comment]
Configuring things to be just a couple minutes works for me. However, the failed pod is still hanging around. If I delete the PVC and then then the pod, a new pod will be created (I think this is due to the ordinal nature of the statefulset). When that new pod is created, it gets scheduled to a node and then fails at startup with

```
[2019/09/18 18:24:04.465 +00:00] [ERROR] [util.rs:327] ["request failed"] [err="Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some(\"duplicated store address: id:105 address:\\\"demo-tikv-2.demo-tikv-peer.tidb22.svc:20160\\\" version:\\\"3.0.1\\\" , already registered by id:6 address:\\\"demo-tikv-2.demo-tikv-peer.tidb22.svc:20160\\\" labels:<key:\\\"host\\\" value:\\\"gke-alpha-tidb-n1-standard-2-375-eae63f05-hdhf\\\" > version:\\\"3.0.1\\\" \") }))"]
```

This seems like a bug in tidb-operator? But it wouldn't be an issue in the first place if we didn't reuse ordinals.

**Comment by cofyc** [comment]
Sorry I missed this. An operation is required to take down the previous TiKV store. The new TiKV pod failed to join the cluster because its address `demo-tikv-2.demo-tikv-peer.tidb22.svc` is used by previous TiKV store which is unreachable but the PD does not know if it's permanently gone. 

There are two methods:

1) delete a TiKV store gracefully (available in pd-ctrl)

```
http DELETE http://<pd_address>:2379/pd/api/v1/store/${id}
```

PD will replicate the data regions from two other replicas.

When the replication factor of data regions on this deleted store reaches 3, the store will be marked  Tombstone.

2) force delete a TiKV store (set the status of TiKV store to Tombstone immediately)

```
http POST http://127.0.0.1:2379/pd/api/v1/store/${id}/state?state=Tombstone
```

When the previous TiKV store is marked Tombstone (permanently deleted from the cluster), its address can be reused.

**Comment by cofyc** [comment]
It seems that it's better to have a controller which integrates cloud providers to recover from this situation in tidb-operator.

**Comment by gregwebs** [comment]
I think we need a [better StatefulSet](https://github.com/gregwebs/kubernetes/pull/1) to be able to fix this properly.

**Comment by tennix** [comment]
> It seems that it's better to have a controller which integrates cloud providers to recover from this situation in tidb-operator.

Yes, I agree we need a cloud controller for tidb-operator to get more power from cloud providers to make the management more automatic.

**Comment by cofyc** [comment]
> I think we need a better StatefulSet to be able to fix this properly. Otherwise after the recovery I end up with 4 pods even though I should only have 3.

Yes, if we want to scale down the cluster by deleting a failed pod in the middle when the new replica pod created by auto-failover is ready, we cannot achieve with current StatefulSet controller.

Or we can disable auto-failover if we will recover the failed pod in place.

**Comment by jhedev** [comment]
Having the same issue on an AWS EKS cluster created using the terraform config found in this repo. I deleted the node manually after roughly half an hour the statefulset was scaled to 4 and a new pod came up while the 3rd one was still erroring.

What would I need to do if I'd like to recover the 3rd pod manually?

**Comment by cofyc** [comment]
hi, @jhedev 

This 3rd pod fails because the node is gone. It can't recover automatically because its local PV is bound to the node. If the node cannot recover, you need to 1) [delete the TiKV store from the cluster](https://github.com/pingcap/tidb-operator/issues/408#issuecomment-533765311), then 2) [delete the pod and its PVC](https://github.com/pingcap/tidb-operator/issues/408#issuecomment-532038900). The StatefulSet controller will create a new pod to replace the failed pod.

On the master branch, we're experimenting with a new statefulset controller ([advanced-statefulset](https://github.com/pingcap/advanced-statefulset)) which supports deleting the pod in the middle permanently.

**Comment by jhedev** [comment]
@cofyc thanks for the quick response. Indeed this helped to recover. The advanced statefulset sounds interesting. Let me know if you need anyone for testing :)

**Comment by cofyc** [comment]
You're welcome ;-) You can join our slack community via this link: https://pingcap.com/tidbslack/ . Our channel is `sig-tidb-operator`.

**Comment by cofyc** [comment]
In [this PR](https://github.com/pingcap/tidb-operator/pull/2119/files#diff-59c4ab87e9fb2d910088555ef70e2be5R286),  I added an e2e test to test how to recover from node deletion (local storage lost) in eks/gke. 

In GKE, it's simpler to use fixed paths and enable `useNodeNameOnly` in local-volume-provisioner. This is because the node name does not change, we can remove the member identifiers of affected PD and TiKV pods and wait for them to start with empty data.
