### ISSUE TITLE
ebs br: dataplane bk in VolumeBackupInitialized is not cleared after vbk is deleted

### ISSUE THREAD

**Issue by BornChanger** [pingcap/tidb-operator#5080]
## Bug Report

**What version of Kubernetes are you using?**

Nightly

**What version of TiDB Operator are you using?**

Nightly

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

1. Issue volume backup CR
2. delete the vbk when a dataplane bk is still in VolumeBackupInitialized status

**What did you expect to see?**
all bk in dataplane is deleted as well.

**What did you see instead?**
the dataplane bk and the pod is left

**Comment by BornChanger** [comment]
Need to verify it's fixed.

**Comment by WangLe1321** [comment]
![image](https://github.com/pingcap/tidb-operator/assets/13897016/25383e12-36bc-4bdf-9018-6407f68e2433)
![image](https://github.com/pingcap/tidb-operator/assets/13897016/8a73219e-d6e3-45b0-bfe0-70b177269ea7)

this issue is fixed by https://github.com/pingcap/tidb-operator/pull/5153 , since we change to record data plane backup information in status of VolumeBackup immediately after the data plane backup is created.
