### ISSUE TITLE
delete restore data pod when restoring will cause restore progress stuck

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb-operator#5297]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**
1. do volumerestore
2. delete restore data pod

**What did you expect to see?**
1. volumerestore success

**What did you see instead?**
1. restore progress stuck
![25122686-be1f-4998-a537-aab07c25ed2a](https://github.com/pingcap/tidb-operator/assets/81375082/a04023e7-127b-4d21-99c5-f9688b2c1323)

**Comment by YuJuncen** [comment]
This may because the previous `recovery_region` hasn't exit. So the restore manager called the `recovery_region` twice, they may promote two different stores to leader so they will race the election eternally(the first store try to become leader due to the first `recovery_region` call and the second store(usually another one) try to become leader due to the second `recovery_region` call). 

I think we need to make all calls to `recovery_region` mutually exclusive. With preempting available -- the second call will abort the first call.

**Comment by zhongmin-amin** [comment]
verified

**Comment by BornChanger** [comment]
Reopen it since the PR is not merged yet.

**Comment by BornChanger** [comment]
The TiVK PR is closed.
