### ISSUE TITLE
[Feature Request] TIDB migration to another K8S cluster

### ISSUE THREAD

**Issue by kkimdev** [pingcap/tidb-operator#565]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Migrating entire K8S to another K8S cluster (e.g., AWS to GKE) ideally without downtime.

**Describe the feature you'd like:**
Documentation or a feature that provides seamless, 0-downtime migration to another K8S cluster.

**Describe alternatives you've considered:**
Backup and restore.  However, some service downtime is unavoidable in this way.

**Teachability, Documentation, Adoption, Migration Strategy:**
Since TIDB is already distributed in nature, I think the easiest way to achieve this is just connecting two TIDB instances across two clusters, then shutting down the original one after fully synced.  I suspect it can be as simple as exposing & specifying an external TIDB endpoint as helm chart values.

**Comment by gregwebs** [comment]
@kkimdev are you familiar with tidb-binlog?

**Comment by kkimdev** [comment]
@gregwebs No, though I've read that it's a tool to perform incremental backup or master-slave synchronization.  Can it be used for master-master synchronization?

Here is the 0 downtime migration flow I was thinking:
1. "Cluster A" connects to "TIDB A". And "Cluster A" is running in production.
2. Create an identical "Cluster B" that connects to "TIDB B", not in production yet.
3. Synchronize "TIDB A" and "TIDB B".
4. Change production DNS to point "Cluster B" instead of "Cluster A", now gradually "Cluster B" will get more traffic and "Cluster A" will get less traffic.
5. After full traffic migration, shut down "Cluster A" and "TIDB A"

**Comment by gregwebs** [comment]
yes, master-master synchronization doesn't make sense for TiDB. Instead of having 2 TiDB clusters you would have one and start creating new (TiKV nodes at least) in a new cluster. If your goal was to change the physical location of the cluster to a different datacenter then you will now have increased latency while writes go to 2 datacenters during the transition (although there are techniques to reduce the transition window and keep a majority in one datacenter to keep latency low if there are no failiures)

Unfortunately, tidb-operator is not currently architected to work with a TiDB deployment across multiple Kubernetes clusters (you should be able to use federated clusters though). However, I do think we will need to eventually provide this ability. It may not be that hard if we can figure out how to join the 2 TiKV deployments together. We will be thinking about architectural improvements for TiDB 4.0 and this issue will come up.

You might consider joining the [community slack channel](https://pingcap.com/tidbslack/) or asking on Reddit/Stack Overflow with more details for your use case.
