### ISSUE TITLE
Install on "normal" K8s?

### ISSUE THREAD

**Issue by Berndinox** [pingcap/tidb-operator#648]
Hy,

there are Guidies on how to Setup on different specific Cloud Providers.
But, how can i install/use the operator on an default K8s Cluster (actuall i do use DO managed K8s)

Thanks, BR

**Comment by aylei** [comment]
Please refer to the [TiDB Operator Setup](https://github.com/pingcap/tidb-operator/blob/master/docs/setup.md)

**Comment by Berndinox** [comment]
thanks @aylei

**Comment by aylei** [comment]
@Berndinox You're welcome, feel free to reopen or file a new issue if you have any trouble following this guide😄

**Comment by Berndinox** [comment]
@aylei Digitalocean is using CSI for mounting blockstorage. Can i use that Storageclass aswell?

**Comment by tennix** [comment]
@Berndinox This issue is already closed, I suggest you join our [community slack](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNjIyNjA5Njk0NTAxLTVmZDkxOWY1ZGZhMDg3YzcwNGU0YmM4ZjIyODRhOTg4MWEwZjJmMGQzZTJlNjllMGY1YzdlNzIxZGE2NzRlMGY) #tidb-operator channel to discuss the usage of tidb-operator.

**Comment by gregwebs** [comment]
@Berndinox note that blockstorage is cloud disk. Last I checked, there is no local SSD option on DO K8s, so I presume that TiDB will perform worse there.
