### ISSUE TITLE
Helm Chart version is not valid Semantic Version

### ISSUE THREAD

**Issue by swdee** [pingcap/tidb-operator#975]
The Helm chart version is listed as `dev` which is not a valid semantic version. 

https://github.com/pingcap/tidb-operator/blob/f91fc5833566104fd24e273ce1b4f08786ab5bdd/charts/tidb-operator/Chart.yaml#L4

This causes a problem when building ones own application chart that uses TiDB as a dependency in a `requirements.yaml` file.

```
Error: dependency "tidb-operator" has an invalid version/constraint format: improper constraint: dev
```

Obviously I can edit the Chart.yaml and set my own version to get around this problem, however it would be nice not to have to do that and for it to be correctly set in the origin source base.

The issue effects all charts; tidb-backup, tidb-cluster, tidb-drainer, tidb-lightning, tidb-operator.

**Comment by tennix** [comment]
@swdee This is intended. The `dev` version indicates that it should only be used in the development and testing environment because we cannot detect the exact version of the installed chart. End users should use the released chart in our chart repo https://charts.pingcap.org

The chart in the source code will be modified during packaging in our CI system.

**Comment by swdee** [comment]
Cool, didn't realise you hosted your own chart repo.
