### ISSUE TITLE
TidbCluster: delete failure component Pod

### ISSUE THREAD

**Issue by LinuxGit** [pingcap/tidb-operator#981]
## Feature Request
**Describe the feature you'd like:**

eg. One of the Pod `tikv-pod-1` in the tidb cluster failed (the  K8s node was down and can't recover), TiDB Operator failover and  start a new `tikv-pod-3`, we want to remove `tikv-pod-1`.

**Comment by tennix** [comment]
There are two options to accomplish this:

* Change the failover logic to delete the old TiKV and create a new TiKV to replace it instead of creating another ordinal TiKV
* Support scale in pod at arbitrary ordinal for statefulset.

The first needs to forcibly delete Pod/PVC/Store, it has risk of losing data.

@cofyc has implemented a [modified statefulset controller](https://github.com/cofyc/advanced-statefulset) that allows scale in at arbitrary ordinal.
